
"use client";

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { useToast } from '@/hooks/use-toast';
import { BrainCircuit, Calendar, CloudDrizzle, Sun, Leaf, Loader2, RefreshCcw, Sparkles, Download } from 'lucide-react';
import { useLanguage } from '@/contexts/language-context';
import { predictSeason, type PredictSeasonOutput } from '@/ai/flows/predict-season';
import { Alert, AlertDescription, AlertTitle } from '../ui/alert';
import { generateDocx } from '@/app/actions/download-report';

const formSchema = z.object({
  cropName: z.string().min(2, 'Please enter a valid crop name.'),
  location: z.string().min(2, 'Please enter a valid location.'),
});

type PredictionState = {
  status: 'idle' | 'loading' | 'success' | 'error';
  data: PredictSeasonOutput | null;
  error: string | null;
};

export function SeasonPredictor() {
  const { t } = useLanguage();
  const { toast } = useToast();
  const [prediction, setPrediction] = useState<PredictionState>({ status: 'idle', data: null, error: null });

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: { cropName: '', location: '' },
  });

  const onSubmit = async (values: z.infer<typeof formSchema>) => {
    setPrediction({ status: 'loading', data: null, error: null });
    
    try {
      const result = await predictSeason(values);
      setPrediction({ status: 'success', data: result, error: null });
    } catch (error) {
      console.error(error);
      const errorMessage = "Failed to get prediction. Please try again.";
      setPrediction({ status: 'error', data: null, error: errorMessage });
      toast({
        variant: "destructive",
        title: "Prediction Failed",
        description: errorMessage,
      });
    }
  };
  
  const reset = () => {
    setPrediction({ status: 'idle', data: null, error: null });
    form.reset();
  }

  const handleDownload = async () => {
    if (!prediction.data) return;
    const { cropName, location } = form.getValues();
    const { sowingPrediction, harvestingPrediction, weatherRisk, alternateCrops } = prediction.data;

    const reportHtml = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Smart Season Prediction Report</title>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            h1, h2, h3 { color: #2E7D32; }
            h1 { font-size: 24px; text-align: center; border-bottom: 2px solid #ccc; padding-bottom: 10px; }
            h2 { font-size: 20px; border-bottom: 1px solid #eee; padding-bottom: 5px; margin-top: 25px; }
            h3 { font-size: 16px; }
            .section { margin-bottom: 20px; border: 1px solid #ddd; padding: 15px; border-radius: 5px; background-color: #f9f9f9; }
            .disclaimer { font-size: 12px; color: #757575; text-align: center; margin-top: 30px; }
            ul { padding-left: 20px; }
            li { margin-bottom: 5px; }
            p { margin: 10px 0; }
            strong { color: #444; }
          </style>
        </head>
        <body>
          <h1>Smart Season Prediction Report</h1>
          <p style="text-align:center;">Generated by FarmFriend on: ${new Date().toLocaleString()}</p>
          
          <div class="section">
            <h2>I. Prediction Details</h2>
            <p><strong>Crop:</strong> ${cropName}</p>
            <p><strong>Location:</strong> ${location}</p>
          </div>
          
          <div class="section">
            <h2>II. AI-Powered Forecast</h2>
            <p><strong>Optimal Sowing Window:</strong> ${sowingPrediction}</p>
            <p><strong>Expected Harvesting Window:</strong> ${harvestingPrediction}</p>
          </div>

          <div class="section">
            <h2>III. Weather Risk Assessment</h2>
            <p>${weatherRisk}</p>
          </div>

          ${alternateCrops.length > 0 ? `
          <div class="section">
            <h2>IV. Alternative Crop Suggestions</h2>
            ${alternateCrops.map(crop => `
              <div>
                <h3>${crop.name}</h3>
                <p><strong>Reason:</strong> ${crop.reason}</p>
              </div>
            `).join('')}
          </div>
          ` : ''}

          <p class="disclaimer">
            This report is generated by an AI assistant using predictive models. It is intended for informational purposes only and should not be considered a substitute for professional agronomic advice. Always consider local conditions and consult with experts.
          </p>
        </body>
      </html>
    `;

    try {
      const base64File = await generateDocx(reportHtml);
      const link = document.createElement('a');
      link.href = `data:application/vnd.openxmlformats-officedocument.wordprocessingml.document;base64,${base64File}`;
      link.download = 'FarmFriend_Season_Prediction_Report.docx';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (error) {
      console.error("Error generating document:", error);
      toast({
        variant: "destructive",
        title: "Download Failed",
        description: "Could not generate the report. Please try again.",
      });
    }
  };

  return (
    <section id="season-predictor" className="w-full">
        <div className="text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl font-headline">
            {t.seasonPredictorTitle}
            </h2>
            <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed mt-4">
            {t.seasonPredictorDescription}
            </p>
        </div>

        <Card className="max-w-2xl mx-auto mt-8 shadow-lg">
            <CardHeader>
                <CardTitle className="flex items-center gap-2">
                    <BrainCircuit className="text-primary" />
                    {t.seasonPredictorCardTitle}
                </CardTitle>
            </CardHeader>
            <CardContent>
                {prediction.status === 'idle' && (
                    <Form {...form}>
                        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                            <FormField
                                control={form.control}
                                name="cropName"
                                render={({ field }) => (
                                <FormItem>
                                    <FormLabel>Your Crop</FormLabel>
                                    <FormControl>
                                        <Input placeholder="e.g., Rice, Wheat" {...field} />
                                    </FormControl>
                                    <FormMessage />
                                </FormItem>
                                )}
                            />
                             <FormField
                                control={form.control}
                                name="location"
                                render={({ field }) => (
                                <FormItem>
                                    <FormLabel>Your Location</FormLabel>
                                    <FormControl>
                                        <Input placeholder="e.g., Punjab, India" {...field} />
                                    </FormControl>
                                    <FormMessage />
                                </FormItem>
                                )}
                            />
                            <Button type="submit" className="w-full">
                                <Sparkles className="mr-2 h-4 w-4" />
                                Get Prediction
                            </Button>
                        </form>
                    </Form>
                )}

                {prediction.status === 'loading' && (
                    <div className="flex flex-col items-center justify-center h-40 gap-2">
                        <Loader2 className="h-12 w-12 animate-spin text-primary" />
                        <p className="text-muted-foreground">AI is analyzing climate data...</p>
                    </div>
                )}

                {prediction.status === 'error' && (
                     <div className="flex flex-col items-center justify-center h-40 gap-4 text-center">
                        <p className="text-destructive">{prediction.error}</p>
                        <Button onClick={reset}>
                            <RefreshCcw className="mr-2 h-4 w-4"/>
                            Try Again
                        </Button>
                    </div>
                )}

                {prediction.status === 'success' && prediction.data && (
                    <div className="space-y-6">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-center">
                           <Card className="bg-secondary/50">
                                <CardHeader>
                                    <CardTitle className="text-lg flex items-center justify-center gap-2"><Sun className="text-primary"/> Sowing Time</CardTitle>
                                </CardHeader>
                                <CardContent>
                                    <p className="text-2xl font-bold">{prediction.data.sowingPrediction}</p>
                                </CardContent>
                           </Card>
                           <Card className="bg-secondary/50">
                                <CardHeader>
                                    <CardTitle className="text-lg flex items-center justify-center gap-2"><Calendar className="text-primary"/> Harvesting Time</CardTitle>
                                </CardHeader>
                                <CardContent>
                                    <p className="text-2xl font-bold">{prediction.data.harvestingPrediction}</p>
                                </CardContent>
                           </Card>
                        </div>
                        
                        <Alert>
                            <CloudDrizzle className="h-4 w-4" />
                            <AlertTitle>Weather Risk Assessment</AlertTitle>
                            <AlertDescription>{prediction.data.weatherRisk}</AlertDescription>
                        </Alert>
                        
                        {prediction.data.alternateCrops.length > 0 && (
                            <div>
                                <h3 className="font-semibold text-lg mb-2 flex items-center gap-2"><Leaf /> Alternative Crop Suggestions</h3>
                                <div className="space-y-2">
                                    {prediction.data.alternateCrops.map(crop => (
                                        <Card key={crop.name}>
                                            <CardContent className="p-3">
                                                <p className="font-bold">{crop.name}</p>
                                                <p className="text-sm text-muted-foreground">{crop.reason}</p>
                                            </CardContent>
                                        </Card>
                                    ))}
                                </div>
                            </div>
                        )}

                        <div className="text-center mt-6 flex justify-center gap-4">
                             <Button onClick={reset}>
                                <RefreshCcw className="mr-2 h-4 w-4"/>
                                New Prediction
                            </Button>
                            <Button variant="outline" onClick={handleDownload}>
                                <Download className="mr-2 h-4 w-4" />
                                Download Report
                            </Button>
                        </div>
                    </div>
                )}
            </CardContent>
        </Card>
    </section>
  );
}
